language: python
python:
#  - "2.6"  # unittest.TestCase doesn't have assertIn in 2.6
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install nose"
  - "pip install coverage"
  - "pip install codacy-coverage"
  - "pip install collective.checkdocs"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=iocextract --cover-xml
  - python setup.py checkdocs
after_success:
  - python-codacy-coverage
